version: '3'
services:
  mysql:
    # image: mysql/mysql-server:5.7
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: gpt_summary
      MARIADB_ROOT_PASSWORD: dodgeram
      MARIADB_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      - mysql-admin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: dodgeram
    networks:
      - mysql-admin

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mysql
  #   networks:
  #     - mysql-admin

networks:
  mysql-admin:

volumes:
  db_data:
